### ISSUE TITLE
[3pts] - Navigation menu to access all pages

### ISSUE THREAD

**Issue by Koshao-sys** [MICHAELKITH/ror_project#52]
- Add a navigation menu to access all pages.

**Comment by brytebee** [comment]
Hi, @Koshao-sys & @MICHAELKITH 👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request

![](https://media.giphy.com/media/OQeKGexhYKVjLaSzPd/giphy.gif)

You have submitted a project, whose PR summary doesn't meet the requirement.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._
